---
title: "descriptive_spatial_statistics_global"
author: "Roberta"
date: "30/1/2023"
output: rmarkdown::github_document
---
First the necessary libraries are installed:
```{r setup}
library(sf); library(tmap); library(spdep)
library(spatialreg)
```

Then, the data is opened. In this case it is the shapefile of the city of Milan, which can be downloaded from the folder "Data" of this repository.
```{r}
MI <- st_read("milano")
coords <- st_centroid(st_geometry(MI))
```

In order to apply Critical cut-off neighborhood, find the minimum distance that can ensure that all centroids have at least one neighborhood.
```{r}
knn1IT <- knn2nb(knearneigh(coords,k=1))
all.linkedT <- max(unlist(nbdists(knn1IT, coords))) 
all.linkedT
```

```{r}
dnb1772 <- dnearneigh(coords, 0, 1772)
dnb2500 <- dnearneigh(coords, 0, 2500)
dnb3000 <- dnearneigh(coords, 0, 3000)

dnb1772.listw <- nb2listw(dnb1772,style="W")
dnb2500.listw <- nb2listw(dnb2500,style="W")
dnb3000.listw <- nb2listw(dnb3000,style="W")
```

```{r}
plot(MI[c("Rent")], main="Rent per square meter in Milan in 2022", nbreaks = 20)
```

```{r}
moran.test(MI$Rent, dnb1772.listw, randomisation=FALSE)
```

```{r}
moran.test(MI$Rent, dnb2500.listw, randomisation=FALSE)
```

```{r}
moran.test(MI$Rent, dnb3000.listw, randomisation=FALSE)
```

```{r}
moran.test(MI$Rent, dnb1772.listw, randomisation=TRUE)
```

```{r}
moran.test(MI$Rent, dnb2500.listw, randomisation=TRUE)
```

```{r}
moran.test(MI$Rent, dnb3000.listw, randomisation=TRUE)
```

```{r}

```